### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by expenses** [repalash/gltf_materials_anisotropy#1]
Hi, I found this extension a few days ago and it seems super cool! Do you have an example of a glTF with this extension being rendered inside threejs or something else?

**Comment by repalash** [comment]
Yes, here is an example(in webgi engine) where watch face and back plate is anisotropic: https://showcase.pixotronics.com/demos/core~viewer.html?m=pixo://gltf/classic-watch.glb?A6

**Comment by expenses** [comment]
Cool, thanks!
